"
I represent an attribute in  ptr.attr


"
Class {
	#name : 'FASTEsopeSegmenntAttribute',
	#superclass : 'FASTEsopeEntity',
	#category : 'FAST-Esope-Entities-Entities',
	#package : 'FAST-Esope-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTEsopeSegmenntAttribute class >> annotation [

	<FMClass: #SegmenntAttribute super: #FASTEsopeEntity>
	<package: #'FAST-Esope-Entities'>
	<generated>
	^ self
]
