"
I represent a slash S__ ptr.attr(S__/1) transformation of ptr.attr(/1)


"
Class {
	#name : 'FASTEsopeDimensionOperator',
	#superclass : 'FASTEsopeEntity',
	#category : 'FAST-Esope-Entities-Entities',
	#package : 'FAST-Esope-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTEsopeDimensionOperator class >> annotation [

	<FMClass: #DimensionOperator super: #FASTEsopeEntity>
	<package: #'FAST-Esope-Entities'>
	<generated>
	^ self
]
