"
comment for name of variable pointer
"
Class {
	#name : #FamixEsopeFortranVariable,
	#superclass : #FamixEsopeEntity,
	#traits : 'FamixTStructuralEntity',
	#classTraits : 'FamixTStructuralEntity classTrait',
	#category : #'Famix-Esope-Entities-Entities'
}

{ #category : #meta }
FamixEsopeFortranVariable class >> annotation [

	<FMClass: #FortranVariable super: #FamixEsopeEntity>
	<package: #'Famix-Esope-Entities'>
	<generated>
	^ self
]
