"
Procedure defined in esope itself


"
Class {
	#name : 'FamixEsopeIntrinsicProcedure',
	#superclass : 'FamixF77IntrinsicRoutine',
	#category : 'Famix-Esope-Entities-Entities',
	#package : 'Famix-Esope-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FamixEsopeIntrinsicProcedure class >> annotation [

	<FMClass: #IntrinsicProcedure super: #FamixF77IntrinsicRoutine>
	<package: #'Famix-Esope-Entities'>
	<generated>
	^ self
]
